{
  "cveId": "CVE-2025-24836",
  "title": "Qardio Heart Health IOS and Android Application and QardioARM A100 Uncaught Exception",
  "description": "With a specially crafted Python script, an attacker could send \ncontinuous startMeasurement commands over an unencrypted Bluetooth \nconnection to the affected device. This would prevent the device from \nconnecting to a clinician's app to take patient readings and ostensibly \nflood it with requests, resulting in a denial-of-service condition.",
  "publishedDate": "2025-02-13T21:55:12.382000+00:00",
  "lastModifiedDate": "2025-02-14T18:11:19.931000+00:00",
  "severity": "HIGH",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:A/AC:H/PR:N/UI:N/S:U/C:L/I:H/A:H",
      "baseScore": 7.1,
      "baseSeverity": "HIGH"
    }
  ],
  "epss": {
    "score": 0.0004,
    "percentile": 12.099
  },
  "riskScore": 39,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["qardio"],
    "products": [
      "heart health ios mobile application",
      "heart health android mobile application",
      "qardioarm"
    ]
  },
  "references": [
    {
      "url": "https://www.cisa.gov/news-events/ics-medical-advisories/icsma-25-044-01",
      "source": "",
      "tags": []
    },
    {
      "url": "https://www.qardio.com/about-us/#contact",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-248"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/24xxx/CVE-2025-24836.json",
        "lastModified": "2025-02-14T18:11:19.931000+00:00"
      }
    ]
  }
}
