{
  "cveId": "CVE-2024-56374",
  "title": "CVE-2024-56374: An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and 4.2 before 4.2.18. Lack o...",
  "description": "An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and 4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed when performing IPv6 validation could lead to a potential denial-of-service attack. The undocumented and private functions clean_ipv6_address and is_valid_ipv6_address are vulnerable, as is the django.forms.GenericIPAddressField form field. (The django.db.models.GenericIPAddressField model field is not affected.)",
  "publishedDate": "2025-01-14T00:00:00+00:00",
  "lastModifiedDate": "2025-02-12T20:31:20.698000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L",
      "baseScore": 5.8,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0007,
    "percentile": 23.166
  },
  "riskScore": 36,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["djangoproject"],
    "products": ["django"]
  },
  "references": [
    {
      "url": "https://docs.djangoproject.com/en/dev/releases/security/",
      "source": "",
      "tags": []
    },
    {
      "url": "https://groups.google.com/g/django-announce",
      "source": "",
      "tags": []
    },
    {
      "url": "https://www.djangoproject.com/weblog/2025/jan/14/security-releases/",
      "source": "",
      "tags": []
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-770"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2024/56xxx/CVE-2024-56374.json",
        "lastModified": "2025-02-12T20:31:20.698000+00:00"
      }
    ]
  }
}
