{
  "cveId": "CVE-2025-0158",
  "title": "IBM EntireX denial of service",
  "description": "IBM EntireX 11.1 could allow a local user to cause a denial of service due to an unhandled error and fault isolation.",
  "publishedDate": "2025-02-06T20:32:03.556000+00:00",
  "lastModifiedDate": "2025-02-22T22:15:35.055000+00:00",
  "severity": "MEDIUM",
  "cvssMetrics": [
    {
      "version": "3.1",
      "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
      "baseScore": 5.5,
      "baseSeverity": "MEDIUM"
    }
  ],
  "epss": {
    "score": 0.0004,
    "percentile": 13.35
  },
  "riskScore": 39,
  "exploitationStatus": "UNKNOWN",
  "affectedSystems": {
    "cpeMatches": [],
    "vendors": ["ibm"],
    "products": ["entirex"]
  },
  "references": [
    {
      "url": "https://www.ibm.com/support/pages/node/7182693",
      "source": "",
      "tags": ["vendor-advisory"]
    }
  ],
  "attackTechniques": [],
  "metadata": {
    "tags": ["CWE-248"],
    "requiresUserInteraction": null,
    "requiresPrivileges": null,
    "attackVector": null,
    "sources": [
      {
        "name": "CVEList",
        "url": "https://github.com/CVEProject/cvelistV5/blob/main/cves/2025/0xxx/CVE-2025-0158.json",
        "lastModified": "2025-02-22T22:15:35.055000+00:00"
      }
    ]
  }
}
